// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class TestPublicationView2JMeter {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty( "webdriver.chrome.driver", "/Users/juancarlosduenaslopez/git/repository/CRIS/chromedriver");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testPublicationView() {
    driver.get("http://localhost:8080/CRIS/");
    driver.manage().window().setSize(new Dimension(1402, 1027));
    driver.findElement(By.linkText("List researchers")).click();
    driver.findElement(By.linkText("7003501614")).click();
    driver.findElement(By.linkText("70349446160")).click();
  }
}
