// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
public class TestLoginUpdateCiteCountTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
   }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testLoginUpdateCiteCount() {
    driver.get("http://localhost:8080/CRIS/");
    driver.manage().window().setSize(new Dimension(1440, 812));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("root");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Researchers list")).click();
    driver.findElement(By.linkText("7003501614")).click();
    driver.findElement(By.linkText("70349446160")).click();
    driver.findElement(By.linkText("70349446160")).click();
    driver.findElement(By.linkText("Researchers list")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.cssSelector("html")).click();
  }
}
